### ISSUE TITLE
集成 libseccomp 库

### ISSUE THREAD

**Issue by Gusabary** [Veiasai/secureMe#2]
开发需要用到 [libseccomp](https://github.com/seccomp/libseccomp) 库，目前的方式是
```bash
apt install libseccomp-dev libseccomp2 seccomp
```
但是我更想用 CMake 把它 include 进来，可是它不像 [yaml-cpp](https://github.com/jbeder/yaml-cpp)，[cxxopts](https://github.com/jarro2783/cxxopts/) 这些库一样本身有 `CMakeLists.txt` 文件
我该怎么做

**Comment by Veiasai** [comment]
#3 

[Cmake集成项目的三种方式](https://zhuanlan.zhihu.com/p/102050750)
