### ISSUE TITLE
target 程序调用危险 syscall 时的操作选择

### ISSUE THREAD

**Issue by Gusabary** [Veiasai/secureMe#4]
目前的设计是两个进程，在子进程中设置好 seccomp 的规则然后 execv target binary，这样即使 target 试图调用一些危险的 syscall 导致退出后，父进程还可以做一些后续的处理。问题在于将危险 syscall 的 seccomp action 设为哪一种比较合适，大概考虑了一下有这么几个选项：
+ `SCMP_ACT_KILL`：一旦试图调用危险 syscall，直接将子进程杀死
  + 优点：简单
  + 缺点：只会打印 Bad System Call，无法得知是由于调用了哪个 sysacll 而退出的
+ `SCMP_ACT_TRAP`：不直接杀死，而是发送一个 `SIGSYS` 信号给子进程，在子进程中 execv 前可以先设置一个 `SIGSYS` handler 让其收到信号后挂起等待父进程获取到导致退出的 syscall 的信息后再将其杀死
  + 优点：可以获取到导致退出的 syscall 的信息
  + 缺点：target 有可能也设置了 `SIGSYS` handler，导致覆盖掉我们设置的 handler
+ `SCMP_ACT_TRACE`：类似 ptrace event，将试图调用危险 syscall 处理成一个 event 交给父进程做进一步操作
  + 优点：可以获取到导致退出的 syscall 的信息
  + 缺点：父进程需要 trace 子进程，可能有 overhead

**Comment by Veiasai** [comment]
为了方便你debug，我建议先实现第二种。

以后可以将第一种也加入，采用配置的方式选用action。
btw，如果是第一种，就不需要两个进程了吧，设置好后运行就行。

**Comment by Veiasai** [comment]
第三种的 “可能overhead”， 有时间再深入试一试吧。

**Comment by Gusabary** [comment]
第二种有个致命问题，[注册好的 signal handler 在调用 execv 时会被清除](https://stackoverflow.com/questions/2333637/is-it-possible-to-signal-handler-to-survive-after-exec)，对于我们的应用场景，无法修改 target 中收到 `SIGSYS` 信号后的行为，和第一种没什么本质区别。
我先做第三种了
