### ISSUE TITLE
seccomp 字符串比较

### ISSUE THREAD

**Issue by Gusabary** [Veiasai/secureMe#6]
在做 FileWhitelist 的时候需要比较 `open` 的第一个参数和配置文件中的 rule，但是 seccomp 的机制不支持字符串比较。
替代方案：当 target 调用 `open` 的时候 trap 进来，父进程再检查参数，性能确实会受到影响，但是暂时也没想到别的办法。
NetworkMonitor 也同理。
相关链接：
+ https://github.com/seccomp/libseccomp/issues/190
+ https://unix.stackexchange.com/questions/492067/how-to-compare-string-values-with-seccomp

**Comment by Veiasai** [comment]
只是open trap的话还行。
而且性能问题也不要过于担心，要实际测一下才行。
